M48
; DRILL file {KiCad 9.0.7} date 2026-04-09T15:46:19-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-09T15:46:19-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X49.5Y-132.0
X49.574Y-66.5
X119.5Y-66.5
X119.5Y-132.0
T2
X98.0Y-87.57
M30
